version: '3'
services:
  gpr-reports-front:
    build: ../gpr-reports
    container_name: gpr-reports-front
    ports:
      - '3000:3000'
    depends_on:
      - gpr-reports-api
    volumes:
      - ../gpr-reports:/app:delegated
    command:
      - sh
      - -c
      - | 
        npm start
  gpr-reports-api:
    build: ../gpr-reports-api
    container_name: gpr-reports-api
    ports:
      - '8000:80'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mysql
    volumes:
      - ../gpr-reports-api:/app:delegated
      - ../gpr-reports-api/docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ../gpr-reports-api/docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
  mysql:
    image: percona:8.0
    container_name: gpr-reports-mysql
    ports:
      - "33072:3306/tcp"
    command: --max_allowed_packet=104857600 --innodb-buffer-pool-size=256M
    environment:
      MYSQL_DATABASE: "gpr-reports"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"